version: "1.0"

linter: jetbrains/qodana-js:2025.2
profile:
  name: qodana.recommended
exclude:
  - name: Eslint
  - name: Syntax errors and unresolved references in JSDoc
  - name: Unresolved variable or type 'JSX'
  - name: Unresolved variable or type 'Element'