/**
 * Notification types enum
 */
export const NotificationType = {
    NEW_OWNERSHIP_REQUEST: "NEW_OWNERSHIP_REQUEST",
    OWNERSHIP_REQUEST_APPROVED: "OWNERSHIP_REQUEST_APPROVED",
    OWNERSHIP_REQUEST_ANALYZING: "OWNERSHIP_REQUEST_ANALYZING",
    OWNERSHIP_REQUEST_REJECTED: "OWNERSHIP_REQUEST_REJECTED",
    NEW_ANIMAL_ADDED: "NEW_ANIMAL_ADDED",
    FOSTERED_ANIMAL_ADOPTED: "FOSTERED_ANIMAL_ADOPTED",
    NEW_OWNERSHIP_ACTIVITY: "NEW_OWNERSHIP_ACTIVITY",
    OWNERSHIP_ACTIVITY_START_REMINDER_USER: "OWNERSHIP_ACTIVITY_START_REMINDER_USER",
    OWNERSHIP_ACTIVITY_END_REMINDER_USER: "OWNERSHIP_ACTIVITY_END_REMINDER_USER",
    OWNERSHIP_ACTIVITY_START_REMINDER_SHELTER_ADMIN: "OWNERSHIP_ACTIVITY_START_REMINDER_SHELTER_ADMIN",
    OWNERSHIP_ACTIVITY_END_REMINDER_SHELTER_ADMIN: "OWNERSHIP_ACTIVITY_END_REMINDER_SHELTER_ADMIN",
    FOSTERING_ACTIVITY_START_REMINDER_USER: "FOSTERING_ACTIVITY_START_REMINDER_USER",
    FOSTERING_ACTIVITY_END_REMINDER_USER: "FOSTERING_ACTIVITY_END_REMINDER_USER",
    FOSTERING_ACTIVITY_START_REMINDER_SHELTER_ADMIN: "FOSTERING_ACTIVITY_START_REMINDER_SHELTER_ADMIN",
    FOSTERING_ACTIVITY_END_REMINDER_SHELTER_ADMIN: "FOSTERING_ACTIVITY_END_REMINDER_SHELTER_ADMIN"
} as const;

export type NotificationType = typeof NotificationType[keyof typeof NotificationType];

/**
 * Notification response from API
 */
export interface Notification {
    id: string;
    type: NotificationType;
    message: string;
    animalId: string | null;
    ownershipRequestId: string | null;
    isRead: boolean;
    createdAt: string;
}